### ISSUE TITLE
Confused by branches

### ISSUE THREAD

**Issue by tobiasstraub** [turngeek/www.turngeek.press#6]
The [gh-pages](https://github.com/turngeek/www.turngeek.press/tree/gh-pages) branch holds the [turngeek.press](http://turngeek.press) website. Why is there a similar version (but looks like an older version) of the website in master branch?

I would suggest, to remove the older version of the website from master branch and move the website from gh-pages branch to the master branch in /docs folder and change the settings to serve the website from master branch.

See [here](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) for more information to serving a website from master branch.

**Comment by marcusschiesser** [comment]
@tobiasstraub Great idea! Didn't know that's possible. I will delete no first the master branch to reduce the confusion a bit.

**Comment by tobiasstraub** [comment]
@marcusschiesser It's a relatively new feature to serve a website from the master branch. Your current solution, by handling the gh-pages as the master branch is also good and a much better solution as before. Thanks for unraveling the cofusion.
